num1 = float(input("Enter First Number : "))
num2 = float(input("Enter Second Number : "))
print()
print("Addition : ", num1 + num2)
print("Subtraction : ", num1 - num2)
print("Multiplication : ", num1 * num2)
print("Division : ", num1 / num2)
