import math
import random


class EmployeePerformanceDistribution:

    def __init__(self, performance_scores):
        self.scores = sorted(list(performance_scores))
        self.n = len(self.scores)

        # Summary Metrics
        self.mean = sum(self.scores) / self.n
        self.variance = sum((x - self.mean) ** 2 for x in self.scores) / self.n
        self.std_dev = math.sqrt(self.variance)
        self.median = self._calculate_median()

    def _calculate_median(self):
        mid = self.n // 2
        if self.n % 2 == 0:
            return (self.scores[mid - 1] + self.scores[mid]) / 2.0
        return float(self.scores[mid])

    def calculate_percentiles(self):
        """Calculates performance tiers (Top 10%, Top 20%, Median, Bottom 10%)."""
        p90_idx = int(0.90 * self.n)
        p80_idx = int(0.80 * self.n)
        p10_idx = int(0.10 * self.n)

        return {
            "Top 10% (Star Performers)": self.scores[p90_idx],
            "Top 20%": self.scores[p80_idx],
            "Median (50th percentile)": self.median,
            "Bottom 10% (PIP Risk)": self.scores[p10_idx],
        }

    def ascii_distribution_chart(self, bins=8, max_bar_width=30):
        """Displays binned ASCII frequency distribution of employee scores."""
        min_val, max_val = min(self.scores), max(self.scores)
        bin_width = (max_val - min_val) / bins

        print("==================================================")
        print("      EMPLOYEE PERFORMANCE SCORE DISTRIBUTION     ")
        print("==================================================")
        print(
            f"{'Score Range':<15} | {'Count':<6} | {'Pct %':<7} | Distribution Bar"
        )
        print("-" * 65)

        for i in range(bins):
            low = min_val + i * bin_width
            high = low + bin_width
            # Count elements in range
            if i == bins - 1:
                count = sum(1 for x in self.scores if low <= x <= high)
            else:
                count = sum(1 for x in self.scores if low <= x < high)

            pct = (count / self.n) * 100
            bar = "█" * int((count / self.n) * max_bar_width * 3)
            range_str = f"[{low:5.1f} - {high:5.1f})"
            print(f"{range_str:<15} | {count:<6d} | {pct:<6.1f}% | {bar}")


# ==============================================================================
# Simulation: 1,000 Employees under Power-Law / Pareto Distribution
# (80% of impact generated by top 20% of employees)
# ==============================================================================
random.seed(42)

# Generate Pareto-distributed scores (alpha=2.5 scaled to 0-100 productivity score)
raw_pareto = [random.paretovariate(alpha=2.5) for _ in range(1000)]
# Normalize and scale scores from ~30 to 100
scaled_scores = [min(100.0, 30.0 + (x - 1.0) * 25.0) for x in raw_pareto]

# Instantiate model
emp_dist = EmployeePerformanceDistribution(scaled_scores)

# 1. Output Summary Metrics
print("==================================================")
print("       EMPLOYEE SUCCESS METRICS SUMMARY           ")
print("==================================================")
print(f"Total Headcount     : {emp_dist.n:,}")
print(f"Mean Score E[X]     : {emp_dist.mean:.2f}")
print(f"Median Score        : {emp_dist.median:.2f}")
print(f"Std Dev (Sigma)     : {emp_dist.std_dev:.2f}")
print(
    f"Skewness Indicator  : Mean > Median ({emp_dist.mean:.1f} > {emp_dist.median:.1f}) -> Right Skewed\n"
)

# 2. Output Percentile Tiers
print("--------------------------------------------------")
print("               PERFORMANCE TIERS                  ")
print("--------------------------------------------------")
for tier, value in emp_dist.calculate_percentiles().items():
    print(f"{tier:<28}: {value:.2f} score")
print()

# 3. Output ASCII Distribution Bins
emp_dist.ascii_distribution_chart(bins=8)